### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by jcubic** [patorjk/figlet.js#128]
I would like to update the API to create Promise based `figlet.preloadFonts` if only one argument is provided. It will not be a breaking change, but right now I need to use code like this:

```javascript
await new Promise((resolve) => figlet.preloadFonts(["Standard"], resolve));
```

in my code, there is a lot of boilerplate. This would be much better:

```javascript
await figlet.preloadFonts(["Standard"]);
```

I can create a PR.

**Comment by patorjk** [comment]
Backwards compatible and no dependency needed - that API update sounds fine to me. Go ahead and make a PR.

**Comment by jcubic** [comment]
I'm updating docs and found `figlet.fonts` but I don't see this function in source code.

**Comment by jcubic** [comment]
Created a PR:

https://github.com/patorjk/figlet.js/pull/129

**Comment by patorjk** [comment]
Thanks, I'll check it out tonight.
