### ISSUE TITLE
bloody font include CYRILLIC symbols

### ISSUE THREAD

**Issue by svarga** [patorjk/figlet.js#16]
Hi. Is it possible to enable support for Cyrillic in BLOODY font, me in my project really need it. I would be very grateful for the help, thank you in advance.

**Comment by patorjk** [comment]
Unfortunately an artist would be needed to design such a font. I ported over Bloody into Figlet, and touched up the letters so it look good in unicode, but a font from scratch in that style would require a lot of work. You would need to contact an artist. 

You can use this editor to create FIGlet font files - http://patorjk.com/figlet-editor/#/edit

So you just need someone to design the letters.

**Comment by svarga** [comment]
Many thanks for the answer!
