### ISSUE TITLE
how to use fig let generated words 

### ISSUE THREAD

**Issue by aruntakkar** [patorjk/figlet.js#18]
i successfully generated the words in cmd  i wanted but i don't know how to use these in html comments of my page now i build them in sublime and copy them We should make some GUI interface for ease

**Comment by patorjk** [comment]
Editor specific updates or task runner specific updates are probably outside the scope of this project. However, if you use the JS task runner Grunt, I've created a plugin that auto-generates the text:

https://github.com/patorjk/grunt-figlet

If you're looking for a simple GUI, I've created this:

http://patorjk.com/software/taag/
