### ISSUE TITLE
Feature Request: Sync function that returns data instead of logging it to console

### ISSUE THREAD

**Issue by philkunz** [patorjk/figlet.js#20]
Hi,
first of all: awesome node module!

Would it be possible for you to implement a Sync function that simply returns data instead of logging it to console? The Async way is fine, however that requires to work with promises which sometimes is overhead.

Thank you and regards
Phil

**Comment by patorjk** [comment]
What do you mean? There's a textSync function that returns text.

I like the promise idea. The text function probably should return a promise.

**Comment by philkunz** [comment]
I'm so sorry. I somehow was under the impression that the function doesn't return the text, but logs it to console directly... My bad.

**Comment by patorjk** [comment]
No worries, I might update the docs to make it a little more clear.

**Comment by websemantics** [comment]
Hi, love this module, .. 
I tried this, but it doesn't seem to be supported in the browser, .. one way could be to preload selected fonts so they are available at run-time?

**Comment by websemantics** [comment]
Create a pull request to fix this issue by providing fonts preload option, https://github.com/patorjk/figlet.js/pull/22
