### ISSUE TITLE
How to break lines?

### ISSUE THREAD

**Issue by ghost** [patorjk/figlet.js#21]
https://github.com/cmatsuoka/figlet has a option :
-t   terminal -- FIGlet asks your terminal how wide it is, and uses
     this to determine when to break lines.  Normally, FIGlet assumes
     80 columns so that people with wide terminals won't annoy the
     people they e-mail FIGlet output to.

How do I use this?

**Comment by patorjk** [comment]
Currently there isn't a way, this is a good idea though and would be easy to add. I'll try and look into this later this week.

**Comment by heisGarvit** [comment]
When can we use this feature?

**Comment by jcubic** [comment]
@patorjk do you accept PRs? There are two open, I may take a look and see if I will be able to create line wrapping.

PS: this project is awesome I use in to demo my library jQuery Terminal https://codepen.io/jcubic/pen/VwvEvmN

**Comment by patorjk** [comment]
Yep, I’ve accepted 19 in total. I’d be open to this feature as long as it didn’t negatively effect other things. I looked into it a long time ago but can’t remember why I didn’t add it.

The two PRs outstanding: one looks like spam (I’ve been meaning to take a closer look and close it) and the other changes the formatting of the library (I prefer PRs to be specific and not so multiple things).

**Comment by jcubic** [comment]
Ok, will create PR, I have already working line wrapping that it don't handle spaces yet. I will use options:

`width` and `whitespaceBreak` maybe, if `width` is set it will check the value of `whitespaceBreak` if it's true it will break the ASCII text on closest whitespae otherwise it will break the words.

**Comment by patorjk** [comment]
Feature added as of version 1.5.0. Release notes here: https://github.com/patorjk/figlet.js/releases/tag/1.5.0
