### ISSUE TITLE
Stick Letters font has problem with Z

### ISSUE THREAD

**Issue by fwangel** [patorjk/figlet.js#26]
(I don't know if this is only a problem in the web service, since I have only tested it there)

Using the Stick Letters font, the output is partially corrupted when typing z or Z.

Steps to reproduce:
http://patorjk.com/software/taag/#p=display&v=0&c=bash&f=Stick%20Letters&t=Customization

Expected output:
```
#   __        __  ___  __          __      ___    __       
#  /  ` |  | /__`  |  /  \  |\/| |  /  /\   |  | /  \ |\ | 
#  \__, \__/ .__/  |  \__/  |  | | /_ /~~\  |  | \__/ | \| 
#                                                          
```

Actual output:
```
#   __        __  ___  __          __      ___    __       
#  /  ` |  | /__`  |  /  \  |\/| |  / @ /\   |  | /  \ |\ | 
#  \__, \__/ .__/  |  \__/  |  | | /_ @/~~\  |  | \__/ | \| 
#                                     @@                     
```

**Comment by fwangel** [comment]
I cannot see the difference between this font and the "JS Stick Letters" font, but that one does not have a problem with Z, so I'm sticking with that one instead.

**Comment by patorjk** [comment]
Thank you for reporting this. I've fixed the Stick Letters font (both in this repo and on the TAAG app). You also appear to be correct about the fonts being the same. I'd remove one of them, but I don't want to mess someone up if they're using one of the two, so I'll just leave them both in.
