### ISSUE TITLE
Figlet.js does not work with Browserify

### ISSUE THREAD

**Issue by websemantics** [patorjk/figlet.js#27]
When I include Figlet.js to the front-end using [browserify](http://browserify.org/), the whole thing stops working because of the `fs` module.

I tried to avoid calling methods that use `fs` mainly by preloading the fonts using `preloadFonts` method.

However, when using `text` or `textSync` methods the `loadFontSync ` method gets triggered in [node.js mode] (https://github.com/patorjk/figlet.js/blob/master/lib/node-figlet.js#L37) which does not check for already loaded fonts as in the case of [browser mode](https://github.com/patorjk/figlet.js/blob/master/lib/figlet.js#L967) 

I created a stop-gap package that solves the problem initially, 
https://github.com/websemantics/figlet-browserify but it would be nice to make necessary changes to the library to make it work in the browser regardless of the package manager,

**Comment by mikermcneil** [comment]
@websemantics nice, thanks for sharing!
