### ISSUE TITLE
How to use figlet on typescript?

### ISSUE THREAD

**Issue by marcoslcosta** [patorjk/figlet.js#31]

**Comment by patorjk** [comment]
I'm not that familiar with TypeScript. This is just a regular JavaScirpt library though, so you'd integrate it into your setup the same way you'd integrate any other JavaScript library.

**Comment by sridharmallela** [comment]
@marcoslcosta  This is how i used figlet into typescript class. Here there is class to print input data with testFiglet method

```js
import * as figlet from 'figlet';

class FigletTest() {

    testFiglet(testData: string) => {
        figlet(testData, (error: any, data: any) => {
            if (error) {
                return process.exit(1);
            }
            console.log(chalk.blue(data));
            console.log('');
            process.exit(0);
        });
    }
}
```

**Comment by marcoslcosta** [comment]
@sridharmallela Thank you, I'm going to test this way soon.
