### ISSUE TITLE
Migrating to ES6

### ISSUE THREAD

**Issue by itaditya** [patorjk/figlet.js#35]
I would love to contribute to this fantastic module and I think migrating to ES6 would minimize the codebase. Can I go ahead ?

**Comment by patorjk** [comment]
What changes/refactoring do you have in mind? I'm assuming some kind of transpling would also be involved. Would Grunt still be used, or another config setup? 

I'm open to an ES6 update, but wouldn't want any of the API in the README to change. Just want to know everything you would be doing.

**Comment by itaditya** [comment]
If we consider the module to run on Nodejs then we don't need to do any transpilation and I don't currently know how the package is working on the frontend, so I'll first try convert for Nodejs only

**Comment by elgs** [comment]
@patorjk it's actually pretty easy, just export whatever you put on module.exports for node. This is future proof. Now even nodejs started to support the ES syntax, so there is no reason to support the require syntax any more. When we move to the real ES syntax (as opposed to the fake one covered up by webpack), the modern web dev can finally get rid of webpack.
