### ISSUE TITLE
Explain character padding: Blank line, left/right whitespace

### ISSUE THREAD

**Issue by a-raccoon** [patorjk/figlet.js#39]
I'm curious if there are specific rhymes or reason for blank lines in some font character sets, or why some have whitepace padding on the right side or left and right side of some or all characters.  Looking for the extended history explanations of how the renderers used to and currently work differently or the same, and what is ideal.  I really would like to take out the blank line paddings, where every character has an extra blank line, ie, a 2 line font uses 3.

**Comment by patorjk** [comment]
I'm not sure. Whoever created the font may have just felt it helped readability when multiple lines of text were converted to ASCII Art text.
