### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by kud** [patorjk/figlet.js#42]
Hello,

It could be great to have a preview of all fonts.

For the moment I do this command: 

```
figlet -l|xargs -I FONT sh -c 'echo "FONT:" && figlet -f "FONT" "Imhotep" && echo "-------------------------"'
```

which works great but it could be built-in.

**Comment by kud** [comment]
With custom text:

```
figlet -l|xargs -I FONT sh -c 'echo "FONT:" && figlet -f "FONT" "'$1'" && echo "-------------------------"'
```

**Comment by jcubic** [comment]
This repo is JS library not CLI, and using demo app you can see all fonts with custom text by clicking this link http://patorjk.com/software/taag/#p=testall&f=Graffiti&t=Type%20Something%20

**Comment by kud** [comment]
Thanks :)
