### ISSUE TITLE
Font name problem

### ISSUE THREAD

**Issue by ulwanski** [patorjk/figlet.js#51]
I just spend a few days, debuging problems with rpm build in my project. I discover, that package was unable to build because of ' character in fonts name (`node_modules/figlet/fonts/Patorjk's?Cheese.flf`), it's causing some strange errors in building package. 
Is there any possibility to change this font name to "PatorjksCheese.flf" or similar?

Fonts causing problems:
- node_modules/figlet/fonts/Patorjk's?Cheese.flf
- node_modules/figlet/importable-fonts/Patorjk's?Cheese.js

**Comment by patorjk** [comment]
I'd need a little more info. That's a valid filename, so I'm confused why it would be causing you build issues. What OS are you using? Are you using that font in your app? If not, you could have your scripts delete that font. If you are using that font, you could create a separate file with a different file name and just point figlet to that file.

**Comment by ulwanski** [comment]
I have error during building rpm package on CentOS 7.
I will use script deleting that font, thanks for help :)
