### ISSUE TITLE
Add "ANSI Regular" font to the font directory

### ISSUE THREAD

**Issue by ea167** [patorjk/figlet.js#54]
Hi,
First, congrats for this great package, used by many IDE extensions!

In many of those extensions (eg. Banner Comments for VSCode), the default font is "ANSI Shadow".
The problem with this font is that it is not readable in the minimap on the right side.

The "ANSI Regular" solves the readability issue, unfortunately it is not included by default in your package. 

The "ANSI Regular" can be found in https://github.com/xero/figlet-fonts or https://github.com/miguelmota/figlet-ansi-regular-font

It would be wonderful if you could add it and consequently make it available in all those extensions that depend on your package.
Thank you!

**Comment by patorjk** [comment]
Sure, I can add this in - I meant to do it last night but it slipped my mind. If it's not in by the end of the weekend just ping me.

**Comment by patorjk** [comment]
Font has been added.

**Comment by ea167** [comment]
Thank you @patorjk!
