### ISSUE TITLE
Possibility to add one empty line at the top/beginning

### ISSUE THREAD

**Issue by MikoSh95** [patorjk/figlet.js#67]
When using the figlet on Gitlab runners the text get's a little messed up since always at the beginning of the line there is worker identifier ([0-0]) in that particular case. It would be nice if you can place empty line at the beginning/top of the figlet so this wouldn't happen.

This is how it looks like:

![image](https://user-images.githubusercontent.com/23083053/114708569-cc334a00-9d2b-11eb-991b-a221f6f7fde1.png)

**Comment by patorjk** [comment]
How are you using it? Can't you just add a new-line to the beginning and end of the output string?

**Comment by MikoSh95** [comment]
Damn, it was dumb question. Of course \n at the beginning solves it. Sorry for bothering!
